<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accessories</name>
   <tag></tag>
   <elementGuidId>1a73abd5-1f81-455a-ba26-b54eab0ca259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[count(. | //*[@class = 'ptour-tabs']) = count(//*[@class = 'ptour-tabs'])][count(. | //*[text() = ' Accessories ']) = count(//*[text() = ' Accessories '])][count(. | //div[@class=&quot;ptour-tabs-container&quot;]/div[@class=&quot;ptour-tabs&quot;]) = count(//div[@class=&quot;ptour-tabs-container&quot;]/div[@class=&quot;ptour-tabs&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ptour-tabs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accessories </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;ptour-tabs-container&quot;]/div[@class=&quot;ptour-tabs&quot;]</value>
   </webElementProperties>
</WebElementEntity>
