<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Colors</name>
   <tag></tag>
   <elementGuidId>2b4225c7-61df-421f-b00c-1febc473b84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[count(. | //*[@class = 'ptour-tabs']) = count(//*[@class = 'ptour-tabs'])][count(. | //*[text() = 'Colors']) = count(//*[text() = 'Colors'])][count(. | //div[@class=&quot;ptour-tabs-container&quot;]/div[@class=&quot;ptour-tabs&quot;]) = count(//div[@class=&quot;ptour-tabs-container&quot;]/div[@class=&quot;ptour-tabs&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ptour-tabs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Colors</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;ptour-tabs-container&quot;]/div[@class=&quot;ptour-tabs&quot;]</value>
   </webElementProperties>
</WebElementEntity>
