<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OtpInput</name>
   <tag></tag>
   <elementGuidId>5e43705a-bf05-44c9-83b5-e83a2b19ce7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/input[1][count(. | //input[@type = 'text' and @placeholder = 'OTP']) = count(//input[@type = 'text' and @placeholder = 'OTP'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>OTP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
