<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>enter the notes in the Notes input box</description>
   <name>notesInputBox</name>
   <tag></tag>
   <elementGuidId>7341a486-5151-49cf-abb0-c8d4495c3ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div/div[2]/textarea</value>
   </webElementProperties>
</WebElementEntity>
