<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>select Public call only checkbox</description>
   <name>checkBoxPubLink</name>
   <tag></tag>
   <elementGuidId>eb3219d2-1c8f-4f81-9f35-4997911b1485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-generator-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div/div[2]/div[3]/div[1]/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
