<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Select country code</description>
   <name>countryCode</name>
   <tag></tag>
   <elementGuidId>da5bd55c-608e-4e4f-a09c-c589b2a9c3d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/select</value>
   </webElementProperties>
</WebElementEntity>
