<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>get a filter screen object element</description>
   <name>filterScreen</name>
   <tag></tag>
   <elementGuidId>f05f4b03-7ccc-467e-a782-da9cab216a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-screen</value>
   </webElementProperties>
</WebElementEntity>
