<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dashboard_MahindraSYouV</name>
   <tag></tag>
   <elementGuidId>5205d58e-a71c-4244-a80e-8a538a0d8b37</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tour-title-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MahindraSYouV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[1]/div[@class=&quot;pano-container&quot;]/div[1]/div[@class=&quot;info-screen info-screen-fade-in&quot;]/div[@class=&quot;topbar topbar-fade-in&quot;]/div[@class=&quot;tour-title&quot;]/div[@class=&quot;tour-title-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
