<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tile_Scorpio</name>
   <tag></tag>
   <elementGuidId>ba61b4bf-2622-48cb-8524-bf0e823646c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[count(. | //*[@class = 'main-thumbnail']) = count(//*[@class = 'main-thumbnail'])][count(. | //*[@data-id = '3']) = count(//*[@data-id = '3'])][count(. | id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[1]/div[@class=&quot;pano-container&quot;]/div[1]/div[@class=&quot;info-screen info-screen-fade-in&quot;]/div[@class=&quot;bookmarks-container bookmarks-container-solidColor main-thumbnails bookmarks-container-fade-in ps-container&quot;]/div[@class=&quot;container container-fade-in&quot;]/div[@class=&quot;thumbnail-sub-container&quot;]/div[@class=&quot;main-thumbnail&quot;]) = count(id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[1]/div[@class=&quot;pano-container&quot;]/div[1]/div[@class=&quot;info-screen info-screen-fade-in&quot;]/div[@class=&quot;bookmarks-container bookmarks-container-solidColor main-thumbnails bookmarks-container-fade-in ps-container&quot;]/div[@class=&quot;container container-fade-in&quot;]/div[@class=&quot;thumbnail-sub-container&quot;]/div[@class=&quot;main-thumbnail&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-thumbnail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[1]/div[@class=&quot;pano-container&quot;]/div[1]/div[@class=&quot;info-screen info-screen-fade-in&quot;]/div[@class=&quot;bookmarks-container bookmarks-container-solidColor main-thumbnails bookmarks-container-fade-in ps-container&quot;]/div[@class=&quot;container container-fade-in&quot;]/div[@class=&quot;thumbnail-sub-container&quot;]/div[@class=&quot;main-thumbnail&quot;]</value>
   </webElementProperties>
</WebElementEntity>
