<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Name</name>
   <tag></tag>
   <elementGuidId>12a2c9cb-2323-4d77-9478-b33770ed0f69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | //*[@placeholder = 'Name']) = count(//*[@placeholder = 'Name'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-container&quot;)/div[@class=&quot;main-container&quot;]/div[@class=&quot;dashboard&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;link-generator&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
