<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rAUz7</name>
   <tag></tag>
   <elementGuidId>7af3df1c-a29f-4ecf-b9eb-de5a9d1b244e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rAUz7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;_3AwwN&quot;]/div[@class=&quot;_1i0-u&quot;]/div[@class=&quot;_3Kxus&quot;]/div[@class=&quot;rAUz7&quot;]</value>
   </webElementProperties>
</WebElementEntity>
