<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1o1sm</name>
   <tag></tag>
   <elementGuidId>7143c52a-7862-40e5-8d10-fe38ba8fa3e0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1o1sm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;_3zJZ2&quot;]/div[@class=&quot;copyable-area&quot;]/div[@class=&quot;_2nmDZ _3D9Wd&quot;]/div[@class=&quot;_9tCEa _1P2Tp&quot;]/div[@class=&quot;vW7d1 _1nHRW&quot;]/span[1]/div[@class=&quot;_1o1sm&quot;]</value>
   </webElementProperties>
</WebElementEntity>
