<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__2R973</name>
   <tag></tag>
   <elementGuidId>5b0f94e7-c56f-4901-b131-ef17c887cb73</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>down-context</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2R973</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>white</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;_3zJZ2&quot;]/div[@class=&quot;copyable-area&quot;]/div[@class=&quot;_2nmDZ&quot;]/div[@class=&quot;_9tCEa&quot;]/div[@class=&quot;vW7d1 _1nHRW&quot;]/div[@class=&quot;_3_7SH _3In2e message-out&quot;]/span[1]/div[@class=&quot;_2DNgV LSBf- _20EE3&quot;]/div[@class=&quot;_38oIx&quot;]/span[@class=&quot;_2R973&quot;]</value>
   </webElementProperties>
</WebElementEntity>
