<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>62f242e6-afc7-4550-8575-4e85f15d0f6a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>send-light</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1FKgS app-wrapper-web bFqKf&quot;]/div[@class=&quot;app _3dqpi two&quot;]/div[@class=&quot;MZIyP&quot;]/div[@class=&quot;_3q4NP _1Iexl&quot;]/span[1]/div[1]/span[@class=&quot;_3rsak&quot;]/div[1]/div[@class=&quot;_2fq0t _1drQ- copyable-area&quot;]/div[@class=&quot;_2sNbV _3ySAH&quot;]/span[2]/div[@class=&quot;_3nfoJ&quot;]/div[@class=&quot;_3hV1n yavlE&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
