<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GK4Lv</name>
   <tag></tag>
   <elementGuidId>57864d80-4c07-42fc-b179-8f7b49867ae9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GK4Lv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-animate-menu-icons-item</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;_3AwwN&quot;]/div[@class=&quot;_1i0-u&quot;]/div[@class=&quot;_3Kxus&quot;]/div[@class=&quot;rAUz7 _3TbsN&quot;]/span[1]/div[@class=&quot;p7FLY&quot;]/div[@class=&quot;_1txFK&quot;]/ul[@class=&quot;_3s1D4&quot;]/li[@class=&quot;_10anr vidHz _14ou2 _3asN5&quot;]/button[@class=&quot;GK4Lv&quot;]</value>
   </webElementProperties>
</WebElementEntity>
