<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Priyanka</name>
   <tag></tag>
   <elementGuidId>594d571a-75fe-4600-80ac-35be8404662c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>matched-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Priyanka</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane-side&quot;)/div[1]/div[1]/div[@class=&quot;RLfQR&quot;]/div[@class=&quot;_2wP_Y&quot;]/div[1]/div[@class=&quot;_2EXPL _1f1zm&quot;]/div[@class=&quot;_3j7s9&quot;]/div[@class=&quot;_2FBdJ&quot;]/div[@class=&quot;_25Ooe&quot;]/span[@class=&quot;_1wjpf&quot;]/span[@class=&quot;matched-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
