<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3</name>
   <tag></tag>
   <elementGuidId>cc762234-d3a2-499d-85b1-d4f043ae5279</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>send-light</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1FKgS app-wrapper-web bFqKf&quot;]/span[3]/div[1]/span[@class=&quot;_3rsak&quot;]/div[@class=&quot;_3gUiM copyable-area&quot;]/div[@class=&quot;_2dA13&quot;]/div[@class=&quot;_1CnF3 _12a60&quot;]/div[@class=&quot;_15JHr&quot;]/div[@class=&quot;_3lLzD&quot;]/div[@class=&quot;_2fq0t copyable-area&quot;]/span[@class=&quot;_1CzIm&quot;]/div[@class=&quot;iHLo1&quot;]/div[@class=&quot;eTCKi&quot;]/div[@class=&quot;_3hV1n yavlE&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
