<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calling Svg</name>
   <tag></tag>
   <elementGuidId>9c271d35-0758-4807-a96e-363b309c913a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//svg[count(. | id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[@class=&quot;calling-page-container&quot;]/div[@class=&quot;calling-page-sub-container&quot;]/div[@class=&quot;calling-page-loader&quot;]/div[@class=&quot;calling-page-call-button-logo&quot;]/svg[@class=&quot;calling-page-call-button-logo&quot;]) = count(id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[@class=&quot;calling-page-container&quot;]/div[@class=&quot;calling-page-sub-container&quot;]/div[@class=&quot;calling-page-loader&quot;]/div[@class=&quot;calling-page-call-button-logo&quot;]/svg[@class=&quot;calling-page-call-button-logo&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calling-page-call-button-logo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 124.18 124.36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[@class=&quot;calling-page-container&quot;]/div[@class=&quot;calling-page-sub-container&quot;]/div[@class=&quot;calling-page-loader&quot;]/div[@class=&quot;calling-page-call-button-logo&quot;]/svg[@class=&quot;calling-page-call-button-logo&quot;]</value>
   </webElementProperties>
</WebElementEntity>
