<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>tag is not available in the database</description>
   <name>linkdetails</name>
   <tag></tag>
   <elementGuidId>6420e185-a437-4320-baa6-55bcf0328699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
