<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_interior</name>
   <tag></tag>
   <elementGuidId>850797dc-93a7-4c80-abad-04928e59965b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>interior</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-container&quot;)/div[@class=&quot;react-panos&quot;]/div[@class=&quot;calling-home-page-container&quot;]/div[1]/div[@class=&quot;pano-container&quot;]/div[1]/div[@class=&quot;info-screen info-screen-fade-in&quot;]/div[@class=&quot;bookmarks-container bookmarks-container-solidColor bookmarks-container-fade-in ps-container&quot;]/div[@class=&quot;container container-fade-in middle&quot;]/div[@class=&quot;options-container&quot;]/div[@class=&quot;thumbnails-container&quot;]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;interior&quot;]</value>
   </webElementProperties>
</WebElementEntity>
