<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_testpublic</name>
   <tag></tag>
   <elementGuidId>8e2df7af-fb0f-45ae-b8d9-f55b5519d9fb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-link-log</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testpublic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-container&quot;]/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;dashboard-subcontainer&quot;]/div[2]/div[1]/div[@class=&quot;container-link-log&quot;]/div[@class=&quot;link-log&quot;]/div[@class=&quot;link-log-cell&quot;]/div[@class=&quot;text-link-log&quot;]</value>
   </webElementProperties>
</WebElementEntity>
