<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Enter the customer name</description>
   <name>customerName</name>
   <tag></tag>
   <elementGuidId>6df70313-82a2-4cbf-895c-4b20c785afb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[5]/div/div[3]/input[count(. | //input[@type = 'text' and @class = 'name-text']) = count(//input[@type = 'text' and @class = 'name-text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[5]/div/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
