<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Get call logs refresh button Object Element</description>
   <name>refreshButton</name>
   <tag></tag>
   <elementGuidId>fc18d83c-25f0-4ce1-bfc5-9b6b9e2755f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>refresh-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[1]/div[1]/div[4]</value>
   </webElementProperties>
</WebElementEntity>
