<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_pagination-icon</name>
   <tag></tag>
   <elementGuidId>572c410c-096c-4c76-882c-f82b401baea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'pagination-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-container&quot;]/div[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;dashboard-subcontainer&quot;]/div[2]/div[1]/div[@class=&quot;container-link-log&quot;]/div[@class=&quot;pagination-footer&quot;]/div[@class=&quot;pagination-container&quot;]/div[@class=&quot;pagination-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
