<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Pagination footer Object</description>
   <name>paginationFooter</name>
   <tag></tag>
   <elementGuidId>43cef0a1-ce7c-4016-881a-9e7c452fdf68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-footer</value>
   </webElementProperties>
</WebElementEntity>
